// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, Targ;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUpwBLT3HqYJN30zhGnfS7H4fRg7l-0r8',
    appId: '1:452203101828:web:2c38d68c600a85bb4c8cd1',
    messagingSenderId: '452203101828',
    projectId: 'myapp-cd36a',
    authDomain: 'myapp-cd36a.firebaseapp.com',
    storageBucket: 'myapp-cd36a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh619K-gl_s9EokK60cAD1dY5-2FVslkI',
    appId: '1:452203101828:android:a47e0ed9b3b91b154c8cd1',
    messagingSenderId: '452203101828',
    projectId: 'myapp-cd36a',
    storageBucket: 'myapp-cd36a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLECw-rJ8I-dLMhdM8hN2NjV-QE45J6RY',
    appId: '1:452203101828:ios:cd475a7bd0cb6d854c8cd1',
    messagingSenderId: '452203101828',
    projectId: 'myapp-cd36a',
    storageBucket: 'myapp-cd36a.appspot.com',
    iosBundleId: 'com.example.project',
  );
}
